[package]
name = "kanzei-llm"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
kanzei-base.workspace = true
tokio.workspace = true
futures.workspace = true
bytes.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
url.workspace = true
async-stream.workspace = true
chrono = "0.4"
dirs.workspace = true

[target.'cfg(windows)'.dependencies]
winreg = "0.52"
